---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: appsmith
  namespace: appsmith
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: appsmith
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appsmith
  namespace: appsmith
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: appsmith
    kind: SecretStore
  target:
    name: appsmith
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        APPSMITH_OAUTH2_GOOGLE_CLIENT_ID: "{{ .APPSMITH_OAUTH2_GOOGLE_CLIENT_ID }}"
        APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET: "{{ .APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET }}"
  data:
    - secretKey: APPSMITH_OAUTH2_GOOGLE_CLIENT_ID
      remoteRef:
        key: "aws-xorro/stage/appsmith"
        property: APPSMITH_OAUTH2_GOOGLE_CLIENT_ID
    - secretKey: APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: "aws-xorro/stage/appsmith"
        property: APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET
