---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-service-account-json
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dex-secret-store
    kind: SecretStore
  target:
    name: google-service-account-json
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        googleAuth.json: "{{ .googleAuth | b64dec }}"
  data:
    - secretKey: googleAuth
      remoteRef:
        key: "aws-xorro/stage/dex_google_config"
