---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-dex
  name: dex
  namespace: dex
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dex-secret-store
  namespace: dex
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: dex
