---
apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-communications
  namespace: botkube
  labels:
    botkube.io/config-watch: "true"
data:
  comm_config.yaml: |
    communications:
      default-group:
        socketSlack:
          appToken: {{ (.botkube_secrets | fromJson).botkube_slack_app_token }}
          botToken: {{ (.botkube_secrets | fromJson).botkube_slack_bot_token }}
          enabled: true
          channels:
            name: nst-stage-deployments
            default:
              bindings:
                executors:
                  - k8s-default-tools
                sources:
                  - k8s-err-events
                  - k8s-recommendation-events
                  - k8s-create-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-botkube
  name: botkube
  namespace: botkube
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: botkube
  namespace: botkube
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: botkube
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube
  namespace: botkube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: botkube
    kind: SecretStore
  target:
    name: botkube-comm-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: botkube-communications
            items:
              - key: comm_config.yaml
  data:
    - secretKey: botkube_secrets
      remoteRef:
        key: "aws-xorro/stage/botkube"