{
 "title": "AWS / Cloudwatch / RDS",
 "description": "Visualize AWS RDS metrics",
 "tags": [
  "cloudwatch",
  "aws"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DatabaseConnections/DiskQueueDepth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "DiskQueueDepth",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReadThroughput/WriteThroughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ReadThroughput",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "WriteThroughput",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReadLatency/WriteLatency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "WriteLatency",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "MaximumUsedTransactionIDs/TransactionLogsGeneration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "MaximumUsedTransactionIDs",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TransactionLogsGeneration",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
     "targets": [
      {
       "metricName": "ClientConnections",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Login Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "LoginFailures",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPUUtilization/FailedSQLServerAgentJobsCount",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "FailedSQLServerAgentJobsCount",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReadIOPS/WriteIOPS/BurstBalance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "BurstBalance",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "SwapUsage/BinLogDiskUsage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "SwapUsage",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "BinLogDiskUsage",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "FreeableMemory/FreeStorageSpace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NetworkReceiveThroughput",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NetworkTransmitThroughput",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "OldestReplicationSlotLag/ReplicaLag",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "OldestReplicationSlotLag",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ReplicaLag",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CPUCreditUsage/CPUCreditBalance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "CPUCreditUsage",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "CPUCreditBalance",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReplicationSlotDiskUsage/TransactionLogsDiskUsage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ReplicationSlotDiskUsage",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TransactionLogsDiskUsage",
       "namespace": "AWS/RDS",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DML Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "metricName": "DMLLatency",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DDL Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "metricName": "DDLLatency",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "metricName": "Deadlocks",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Active Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "metricName": "ActiveTransactions",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "SampleCount"
      }
     ]
    },
    {
     "title": "Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "metricName": "Queries",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "RDS Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream, @log\n| filter @logStream = \"${dbinstanceidentifier}\" \n| filter @message like 'ERROR'\n| sort @timestamp desc\n| limit 10000",
     "logGroups": [
      {
       "accountId": "011528281799",
       "arn": "arn:aws:logs:ap-southeast-1:011528281799:log-group:/aws/rds/cluster/stage/postgresql:*",
       "name": "/aws/rds/cluster/stage/postgresql"
      }
     ],
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "ap-southeast-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "RDS Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, @message \n| filter @message like /ERROR/ \n| stats count(*) by bin(1m)",
     "logGroups": [
      {
       "accountId": "011528281799",
       "arn": "arn:aws:logs:ap-southeast-1:011528281799:log-group:/aws/rds/cluster/stage/postgresql:*",
       "name": "/aws/rds/cluster/stage/postgresql"
      }
     ],
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "ap-southeast-1",
     "statistic": "SampleCount",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  }
 ]
}