service:
  fullNameOverride: &name "xorro-notification-service"
  NST: &env
    environment: "stage"
    project: "xorro"
    vertical: "xorro"
  workload:
    enabled: true
    scheduling:
      minAvailable: 1
    deployment:
      replicas: 1
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 1
    podTemplate:
      annotations:
        argocd.argoproj.io/sync-wave: "1"
        argocd.argoproj.io/sync-options: "Prune=false"
        config.linkerd.io/skip-outbound-ports: "8200,3306"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/role: *name
        vault.hashicorp.com/agent-inject-default-template: 'json'
        vault.hashicorp.com/agent-inject-secret-secrets.yml: 'secret/data/xorro/xorro-notification-service'
        vault.hashicorp.com/agent-inject-template-secrets.yml: |
          {{- with secret "secret/data/xorro/xorro-notification-service" -}}
            {{ .Data.data.secrets }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-xorro133f3.json: 'secret/data/xorro/xorro-notification-service'
        vault.hashicorp.com/agent-inject-template-xorro133f3.json: |
          {{- with secret "secret/data/xorro/xorro-notification-service" -}}
            {{ .Data.data.xorro133f3  }}
          {{- end -}}
      nodeSelector:
        nst.com/app-type: "xorro"
      tolerations:
        - key: "nst.com/app-type"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - *name
              topologyKey: "kubernetes.io/hostname"  # This key ensures pods are spread across nodes
      defaultContainer:
        image:
          name: 024848447392.dkr.ecr.ap-southeast-1.amazonaws.com/xorro/xorro-notification-service
          tag: "v1.78.2"
        containerPorts:
          - containerPort: &http 8081
        env:
          - name: MICRONAUT_CONFIG_FILES
            value: "file:/vault/secrets/secrets.yml"
          - name: APP-MAIL_SMTP_PORT
            value: "587"
          - name: MICRONAUT_ENVIRONMENTS
            value: "staging"
          - name: APP-PUSH_NOTIFICATION_FCM_KEYPATH
            value: "/vault/secrets/xorro133f3.json"
          - name: APP-PUSH_NOTIFICATION_FCM_PROJECT
            value: "xorro-133f3"
          - name: APP-MAIL_SMTP_FROM
            value: "notifications@xorro-stage.com"
          - name: JPA_DEFAULT_PROPERTIES_HIBERNATE_SHOW_SQL
            value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /health
            port: *http
        readinessProbe:
          httpGet:
            path: /health
            port: *http
        livenessProbe:
          httpGet:
            path: /health
            port: *http
  service:
    enabled: true
    ports:
      - name: http
        port: *http
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60
  monitoring:
    enabled: true
    scheme: http
    port: http
    path: /prometheus
    interval: 60s          
