---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: xorro
spec:
  template:
    spec:
      taints:
        - key: nst.com/app-type
          value: xorro
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]
        - key: nst.com/app-type
          operator: Exists
      nodeClassRef:
        name: default
  limits:
    cpu: 50
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 24h
