---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zipkin-secrets
  namespace: zipkin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zipkin-ss
    kind: SecretStore
  target:
    name: zipkin-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        ES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "aws-xorro/stage/helm_opensearch"
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: zipkin-ss
  namespace: zipkin
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: zipkin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-zipkin
  name: zipkin
  namespace: zipkin
