provider: emissary
virtualServices:
  default:
    enabled: true
    certificate:
      create: true
    hosts:
      - zipkin.xorro-stage.com
    httpRoutes:
      - match:
          - uri:
              prefix: /
        action:
          route:
            - host: zipkin.zipkin
              port: 9411
        options:
          allow_upgrade:
            - websocket
