service:
  fullNameOverride: &name "xorro-moonpay-service"
  NST: &env
    environment: "stage"
    project: "xorro"
    vertical: "xorro"
  workload:
    enabled: true
    scheduling:
      minAvailable: 1
    deployment:
      replicas: 1
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 1
    podTemplate:
      annotations:
        config.linkerd.io/skip-outbound-ports: "8200,3306"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/role: xorro-moonpay-service
        vault.hashicorp.com/agent-inject-secret-secrets.env: 'secret/data/xorro/xorro-moonpay-service'
        vault.hashicorp.com/agent-inject-template-secrets.env: |
          {{- with secret "secret/data/xorro/xorro-moonpay-service" -}}
            {{ .Data.data.env }}
          {{- end -}}
      nodeSelector:
        nst.com/app-type: "xorro"
      tolerations:
        - key: "nst.com/app-type"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - *name
              topologyKey: "kubernetes.io/hostname"
      defaultContainer:
        image:
          name: 024848447392.dkr.ecr.ap-southeast-1.amazonaws.com/xorro/xorro-moonpay-service
          tag: "v1.17.0"
        containerPorts:
          - containerPort: &http 3000
        env:
          - name: NODE_ENV
            value: "development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /health
            port: *http
        readinessProbe:
          httpGet:
            path: /health
            port: *http
        livenessProbe:
          httpGet:
            path: /health
            port: *http
  service:
    enabled: true
    ports:
      - name: http
        port: *http
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60
