---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-admin-secrets
  namespace: postgres-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres-admin-ss
    kind: SecretStore
  target:
    name: postgres-admin-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
  data:
    - secretKey: password
      remoteRef:
        key: "aws-xorro/stage/pgadmin"
        property: password
    - secretKey: username
      remoteRef:
        key: "aws-xorro/stage/pgadmin"
        property: username
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: postgres-admin-ss
  namespace: postgres-admin
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: postgres-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-postgres-admin
  name: postgres-admin
  namespace: postgres-admin
