---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-listeners
  namespace: argocd
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: 024848447392.dkr.ecr.ap-southeast-1.amazonaws.com
    chart: nst/helm/service
    targetRevision: v1.0.0
    helm:
      version: v3
      values: |
        NST:
          environment: stage
          vertical: xorro
          project: api
          tenant: public
        listener:
          enabled: true
          listeners:
            - port: 8443
              protocol: HTTPS
