provider: emissary
virtualServices:
  default:
    enabled: true
    certificate:
      create: true
    hosts:
      - mock.xorro-stage.com
    httpRoutes:
      - match:
          - uri:
              prefix: /
        action:
          route:
            - host: mock-service.xorro
              port: 8081