---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rabbitmq-ss
    kind: SecretStore
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        rabbitmq-password: "{{ .rabbitmq_password }}"
        rabbitmq-erlang-cookie: "{{ .rabbitmq_erlang_cookie }}"
  data:
    - secretKey: rabbitmq_password
      remoteRef:
        key: "aws-xorro/stage/rabbitmq"
        property: rabbitmq_password
    - secretKey: rabbitmq_erlang_cookie
      remoteRef:
        key: "aws-xorro/stage/rabbitmq"
        property: rabbitmq_erlang_cookie
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: rabbitmq-ss
  namespace: rabbitmq
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: rabbitmq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-rabbitmq
  name: rabbitmq
  namespace: rabbitmq
