service:
  fullNameOverride: &name "xorro-doc-service"
  NST: &env
    environment: "stage"
    project: "xorro"
    vertical: "xorro"
  workload:
    enabled: true
    scheduling:
      minAvailable: 1
    deployment:
      replicas: 1
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 1
    podTemplate:
      nodeSelector:
        nst.com/app-type: "xorro"
      tolerations:
        - key: "nst.com/app-type"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - *name
              topologyKey: "kubernetes.io/hostname"  # This key ensures pods are spread across nodes
      defaultContainer:
        image:
          name: 024848447392.dkr.ecr.ap-southeast-1.amazonaws.com/xorro/xorro-doc-service
          tag: "v1.45.1"
        containerPorts:
          - containerPort: &http 8085
        env:
          - name: MICRONAUT_ENVIRONMENTS
            value: "staging"
          - name: SWAGGER_SERVICES_SOMA_SERVICE_BASE_URL
            value: "http://soma-service:8091"
          - name: SWAGGER_SERVICES_SOMA_SERVICE_SWAGGER_URL
            value: "/swagger/soma-service-1.0.yml"
          - name: SWAGGER_SERVICES_CAMPAIGN_SERVICE_BASE_URL
            value: "http://xorro-campaign-service:8083"
          - name: SWAGGER_SERVICES_CAMPAIGN_SERVICE_SWAGGER_URL
            value: "/swagger/campaign-service-1.0.yml"
          - name: SWAGGER_SERVICES_XORRO_WALLET_SERVICE_BASE_URL
            value: "http://xorro-wallet-service:8094"
          - name: SWAGGER_SERVICES_XORRO_WALLET_SERVICE_SWAGGER_URL
            value: "/swagger/xorro-wallet-service-1.0.yml"
          - name: SWAGGER_SERVICES_XORRO_AUTH_SERVICE_BASE_URL
            value: "http://xorro-auth-service:8084"
          - name: SWAGGER_SERVICES_XORRO_AUTH_SERVICE_SWAGGER_URL
            value: "/swagger/xorro-auth-service-1.0.yml"
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /health
            port: *http
        readinessProbe:
          httpGet:
            path: /health
            port: *http
        livenessProbe:
          httpGet:
            path: /health
            port: *http
  service:
    enabled: true
    ports:
      - name: http
        port: *http
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60
  monitoring:
    enabled: true
    scheme: http
    port: http
    path: /prometheus
    interval: 60s          
