apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: &repo git@github.com:newsocialtheory/argo-xorro-stage.git
        revision: HEAD
        directories:
          - path: infra/infra-apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      labels: {}
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: infra
      sources:
        - repoURL: *repo
          path: "{{path}}"
          targetRevision: HEAD
          helm:
            releaseName: "{{path.basename}}"
            parameters:
              - name: "external-dns-aws.domainFilters[0]"
                value: "prod-build.sg.nucleus.local"
            valueFiles:
              - $valuesRepo/{{path}}/values.yaml
        - repoURL: *repo
          targetRevision: HEAD
          ref: valuesRepo
      destination:
        name: in-cluster
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
