---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  namespace: grafana
data:
  config.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: nst-stage-alerts
        receivers:
          - uid: nst-stage-alerts
            type: slack
            settings:
              url: "{{ (.grafana_secrets | fromJson).alert_slack_webhook }}"
            disableResolveMessage: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-contact-points
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana
    kind: SecretStore
  target:
    name: grafana-contact-points
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          grafana_alert: "1"
      engineVersion: v2
      templateFrom:
        - configMap:
            name: grafana-contact-points
            items:
              - key: config.yaml
  data:
    - secretKey: grafana_secrets
      remoteRef:
        key: "aws-xorro/stage/grafana"
