---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-grafana
  name: grafana
  namespace: grafana
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana
  namespace: grafana
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: grafana
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana
    kind: SecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        admin-password: "{{ .adminPassword }}"
        admin-user: "admin"
        client_id: "{{ .clientId }}"
        client_secret: "{{ .clientSecret }}"
        opensearch_password: "{{ .opensearch_password }}"
        opensearch_user: "{{ .opensearch_user }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: "aws-xorro/stage/grafana"
        property: adminPassword
    - secretKey: clientId
      remoteRef:
        key: "aws-xorro/stage/grafana"
        property: dex_client_id
    - secretKey: clientSecret
      remoteRef:
        key: "aws-xorro/stage/grafana"
        property: dex_client_secret
    - secretKey: opensearch_password
      remoteRef:
        key: "aws-xorro/stage/grafana"
        property: opensearch_password
    - secretKey: opensearch_user
      remoteRef:
        key: "aws-xorro/stage/grafana"
        property: opensearch_user