---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-imgproxy-imgproxy-service-account
  name: imgproxy-imgproxy-service-account
  namespace: imgproxy