---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-kubewatch
  name: kubewatch
  namespace: kubewatch
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubewatch
  namespace: kubewatch
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: kubewatch
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubewatch
  namespace: kubewatch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubewatch
    kind: SecretStore
  target:
    name: kubewatch
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        KW_SLACK_WEBHOOK_URL: "{{ .KW_SLACK_WEBHOOK_URL }}"
  data:
    - secretKey: KW_SLACK_WEBHOOK_URL
      remoteRef:
        key: "aws-xorro/stage/kubewatch"
        property: alert_slack_webhook