provider: emissary
virtualServices:
  default:
    enabled: true
    certificate:
      create: true
    hosts:
      - sso.xorro-stage.com
    httpRoutes:
      - match:
          - uri:
              prefix: /
        action:
          route:
            - host: dex.dex
              port: 5556
