---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cert-manager-secrets-store
  namespace: cert-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cert-manager-secrets-store
    kind: SecretStore
  target:
    name: cert-manager-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        apiToken: "{{ .apiToken }}"
  data:
    - secretKey: apiToken
      remoteRef:
        key: "aws-xorro/stage/cloudflare_api_token"
        property: apiToken
