---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secrets
  namespace: external-dns-cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-dns-cloudflare-ss
    kind: SecretStore
  target:
    name: external-dns-cloudflare-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: opaque
      data:
        cloudflare_api_token: "{{ .apiToken }}"
  data:
    - secretKey: apiToken
      remoteRef:
        key: "aws-xorro/stage/cloudflare_api_token"
        property: apiToken
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-dns-cloudflare-ss
  namespace: external-dns-cloudflare
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-dns-cloudflare
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::011528281799:role/stage-eks-external-dns-cloudflare
  name: external-dns-cloudflare
  namespace: external-dns-cloudflare
