name: Scale Up Services

on:
  schedule:
    - cron: "0 0 * * 1-5"  # 8 AM HKT Monday–Friday
  workflow_dispatch:  # optional manual trigger

permissions:
  contents: write

jobs:
  scale-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set replicaCount to 1
        run: |
          find xorro/xorro-apps -maxdepth 2 -type f -name values.yaml -exec sed -i 's/replicas: [0-9]\+/replicas: 1/' {} +
          find xorro/xorro-apps -maxdepth 2 -type f -name values.yaml -exec sed -i 's/minAvailable: [0-9]\+/minAvailable: 1/' {} +
          find xorro/xorro-apps -maxdepth 2 -type f -name values.yaml -exec sed -i '/autoscaling:/,/^[^[:space:]]/s/enabled: false/enabled: true/' {} +

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git diff
          git add .
          git commit -m "scale up replicas to normal  [automated]" || echo "No changes to commit"
          git push
